server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://product:8080
              predicates:
                - Path=/api/product/**

            - id: order-service
              uri: http://order:8080
              predicates:
                - Path=/api/order/**

            - id: inventory-service
              uri: http://inventory:8080
              predicates:
                - Path=/api/inventory/**

            - id: product-api-docs
              uri: http://product:8080
              predicates:
                - Path=/aggregate/product-service/api-docs
              filters:
                - RewritePath=/aggregate/product-service/api-docs, /api-docs

            - id: order-api-docs
              uri: http://order:8080
              predicates:
                - Path=/aggregate/order-service/api-docs
              filters:
                - RewritePath=/aggregate/order-service/api-docs, /api-docs

            - id: inventory-api-docs
              uri: http://inventory:8080
              predicates:
                - Path=/aggregate/inventory-service/api-docs
              filters:
                - RewritePath=/aggregate/inventory-service/api-docs, /api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /aggregate/product-service/api-docs
      - name: Order Service
        url: /aggregate/order-service/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: TRACE
