apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          command: ["bash", "-c", "unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run"]
          ports:
            - containerPort: 8081

          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry

            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://broker:9092

            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
              
            - name: SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID
              value: "schema-registry-cluster"
            
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: _schemas
              
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT

---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  type: ClusterIP
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081