global:
  scrape_interval: 10s

scrape_configs:

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]
        labels:
           application: 'api-gateway' 

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order:8080"]
        labels:
           application: 'order' 

  - job_name: "inventory-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["inventory:8080"]
        labels:
           application: 'inventory' 
      
  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product:8080"]
        labels:
          application: 'product'  
  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification:8080"]
        labels:
           application: 'notification' 

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
